spring: 
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: <GOOGLE_CLIENT_ID>
                        client-secret: <GOOGLE_CLIENT_SECRET>
            resourceserver:
                jwt:
                    issuer-uri: https://accounts.google.com




